In [2]:
import tensorflow as tf

In [3]:
var = tf.Variable('dummy string', tf.string)
num = tf.Variable(34, tf.int16)
flt = tf.Variable(4.323, tf.float64)

In [5]:
# rank/degree of tensors is the number of dimensions involved in the tensor
# normal inputs (like; var, num and flt defined above) are 0D, a list is of 1D, a singly
# nested list is of 2D

In [46]:
rank1_tensor = tf.Variable(['test', 'check'], tf.string)
rank2_tensor = tf.Variable([['console', 'alert', 'prompt'], ['bengoshi', 'kawaii', 'hito']], tf.string)
demo_tensor = tf.Variable([['alert', 'prompt'], ['kawaii', 'hito'], ['soy', 'toy']], tf.string)

In [49]:
# shape simply tells the amount of elements in each dimension (it doesn't tell the rank)
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))
print(tf.rank(demo_tensor))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [51]:
print(rank1_tensor.shape, rank2_tensor.shape, demo_tensor.shape)
# this would normally yield a tuple of the (elemInfirstDim, elemInsecDim...)
# typically should be (2) (2, 3) and (3, 2)

(2,) (2, 3) (3, 2)


In [52]:
tensor = tf.ones([1, 2, 3]) 
# a single list, in it two lists, in each, three elements (of ones)
# firstDim => one stuff, secDim => two stuff (inside the 1 stuff confirmed to be a list), 
# thirdDim => three stuff (inside each of the two stuff, now also confirmed to be lists)
rank1_tensor.shape
print(tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [55]:
new_tensor = tf.reshape(tensor, [2, 3, 1])
# two lists, in each three lists, in each one element
print(new_tensor)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [61]:
mod_tensor = tf.reshape(new_tensor, [3, -1])
# three lists off of new_tensor, -1 => implies letting tensorflow figure out how many elements 
# will be in each of those three lists; and the shape would be printed in the result

In [62]:
print(mod_tensor)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [63]:
# important note: when carrying the reshame method, the multiplication of all numbers in the
# parameter of the new item tells us the total number of elements to expect in the output

In [64]:
# types of constant include variable (used already), constant, placeholder and sparseTensor

In [66]:
with tf.Session() as sess: # this should create a session using the default graph
    tensor.eval()

AttributeError: module 'tensorflow' has no attribute 'Session'